#!/bin/sh

# wgrep: search a web page for given regex. It uses links(1) for dumping
#	out only the text of the page, and then grepping it
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>. 

function version () {
	echo '0.1'
}

function help () {
	echo 'Usage: wgrep [-c | -h | -v] url regex'
}

COLOR=''

while getopts 'chv' opt
do
	case $opt in
	c)	COLOR="--color"; shift;;
	h)	help;		exit 0;;
	v)	version;	exit 0;;
	\?)	help;		exit 1;;
	esac
done

if [ $# -gt 1 ]
then
	links -dump "$1" | grep $COLOR "$2" 
else
	help
	exit 1
fi
